----------------
-- RESTRIÇÕES --
----------------

CREATE TRIGGER restringir_portagemtradicional
BEFORE INSERT on PortagemTradicional
FOR EACH ROW		
DECLARE TIPOPORTAGEM integer;
BEGIN

SELECT TIPOPORTAGEM FROM AUTOESTRADA WHERE CODAUTOESTRADA = :new.CODAUTOESTRADA

if(TIPOPORTAGEM = 2){
	NEGA
}		
END;


CREATE TRIGGER restringir_portico
BEFORE INSERT on Portico
FOR EACH ROW
DECLARE TIPOPORTAGEM integer;		
BEGIN

SELECT TIPOPORTAGEM FROM AUTOESTRADA WHERE CODAUTOESTRADA = :new.CODAUTOESTRADA

if(TIPOPORTAGEM = 1){
	NEGA
}		
END;