CREATE OR REPLACE VIEW silver_sem_pssar_ligacoes_A3 AS(
SELECT C.NOME FROM CLIENTE C, DISPOSITIVO_VEICULO DV, DISPOSITIVO D 
WHERE C.NIF = D.CLIENTENIF AND D.NR_SERIE = DV.NRSERIEDISPOSITIVO AND  
C.TIPOCLIENTE = 'Silver' AND DV.MATRICULAVEICULO NOT IN
(SELECT DV.MATRICULAVEICULO FROM PASSAGEMPORTICO PP,  DISPOSITIVO_VEICULO DV 
WHERE  DV.MATRICULAVEICULO = PP.MATRICULAVEICULO AND PP.CODAUTOESTRADA NOT IN 
(SELECT A.CODAUTOESTRADA FROM AUTOESTRADA A, LIGACAO L
 WHERE (L.CODAUTOESTRADA1 ='A3' AND A.CODAUTOESTRADA =L.CODAUTOESTRADA2) OR (L.CODAUTOESTRADA2 ='A3' AND A.CODAUTOESTRADA =L.CODAUTOESTRADA1)))
 AND DV.MATRICULAVEICULO NOT IN
(SELECT DV.MATRICULAVEICULO FROM REGISTOENTRADA RE,  DISPOSITIVO_VEICULO DV 
WHERE  DV.MATRICULAVEICULO = RE.MATRICULAVEICULO AND RE.CODAUTOESTRADA NOT IN 
(SELECT A.CODAUTOESTRADA FROM AUTOESTRADA A, LIGACAO L
 WHERE (L.CODAUTOESTRADA1 ='A3' AND A.CODAUTOESTRADA =L.CODAUTOESTRADA2) OR (L.CODAUTOESTRADA2 ='A3' AND A.CODAUTOESTRADA =L.CODAUTOESTRADA1))));