--View 3

CREATE VIEW "MAIOR_FACTURACAO_GOLD" AS
SELECT DISTINCT C.NOME, EXTRACT(YEAR FROM CM.DATAEMISSAO) FROM
CLIENTE C, COBRANCAMENSAL CM WHERE
C.NIF=CM.CLIENTENIF
AND C.TIPOCLIENTE='Gold'
AND CM.VALORTOTAL=MAX(CM.VALORTOTAL)
ORDER BY EXTRACT(YEAR FROM CM.DATAEMISSAO);

