/*FUNCAO 2:
Funnco que, para uma dada autoestrada de portagens tradicionais e num
determinado periodo, permita devolver a relacao entre o numero de veiculos
que efetuaram viagens com o dispositivo inativo e o numero de veiculos que
efetuaram viagens e nao possuem dispositivo. Considera-se que uma viagem e
um percurso efetuado entre duas portagens, mesmo nos casos em que uma das
portagens (entrada ou saida) nao foi registada.

func_relacao_veiculo_tradicional (ae_id ,data_ini, data_fim)
*/

CREATE OR REPLACE FUNCTION FUNC_RELACAO_VEICULO_TRADICIONAL (AE_ID AUTOESTRADA.CODAUTOESTRADA%TYPE, DATA_INI DATE, DATA_FIM DATE) 
RETURN NUMBER IS

QTD_INACTIVO_1 NUMBER;
QTD_INACTIVO_2 NUMBER;
QTD_INACTIVO NUMBER;
QTD_SEM_DISP_1 NUMBER;
QTD_SEM_DISP_2 NUMBER;
QTD_SEM_DISP NUMBER;
RATIO NUMBER;

BEGIN

--CONTAR INACTIVOS

SELECT COUNT(*) INTO QTD_INACTIVO_1 FROM REGISTOSAIDA RS WHERE RS.ESTADODISPOSITIVO=0
AND RS.DATA>DATA_INI AND RS.DATA<DATA_FIM AND VERIFICA_ESTADO(RS.MATRICULAVEICULO,RS.DATA)<>-1;

SELECT COUNT(*) INTO QTD_INACTIVO_2 FROM REGISTOENTRADA RE, REGISTOSAIDA RS WHERE RS.NRREGISTOENTRADA=RE.NRREGISTOENTRADA
AND RE.ESTADODISPOSITIVO=0
AND RE.DATAREG>DATA_INI AND RE.DATAREG<DATA_FIM
AND RE.NRREGISTOENTRADA NOT IN (SELECT RS.NRREGISTOENTRADA FROM REGISTOSAIDA RS) AND VERIFICA_ESTADO(RE.MATRICULAVEICULO,RE.DATAREG)<>-1;

QTD_INACTIVO:=QTD_INACTIVO_1+QTD_INACTIVO_2;


--CONTAR VEICULOS SEM DISPOSITIVO

SELECT COUNT(*) INTO QTD_SEM_DISP_1 FROM REGISTOSAIDA RS WHERE RS.ESTADODISPOSITIVO=0
AND RS.DATA>DATA_INI AND RS.DATA<DATA_FIM AND VERIFICA_ESTADO(RS.MATRICULAVEICULO,RS.DATA)=-1;

SELECT COUNT(*) INTO QTD_SEM_DISP_2 FROM REGISTOENTRADA RE, REGISTOSAIDA RS WHERE RS.NRREGISTOENTRADA=RE.NRREGISTOENTRADA
AND RE.ESTADODISPOSITIVO=0
AND RE.DATAREG>DATA_INI AND RE.DATAREG<DATA_FIM
AND RE.NRREGISTOENTRADA NOT IN (SELECT RS.NRREGISTOENTRADA FROM REGISTOSAIDA RS) AND VERIFICA_ESTADO(RE.MATRICULAVEICULO,RE.DATAREG)=-1;

QTD_SEM_DISP:=QTD_SEM_DISP_1+QTD_SEM_DISP_2;


-- CALCULA RELACAO ENTRE OS INACTIVOS E OS SEM DISPOSITIVO

RATIO:=QTD_INACTIVO/QTD_SEM_DISP;

RETURN RATIO;

END;
